name: itvlist

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:  
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x          

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run IPJD
        run: python ${{ github.workspace }}/ipjd.py
        
      - name: 提交更改
        run: |
          git config --local user.email "lei123-99@163.com"
          git config --local user.name "lei123-99"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
